name: Build and Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/two-tier-backend:latest . --push

      - name: Save private key for SSH access
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: SSH into EC2 and update Flask container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/two-tier-backend:latest
            docker stop flask || true
            docker rm flask || true
            docker run -d --name flask --network two-tier -p 5000:5000 \
              -e MYSQL_HOST=10.0.2.100 \
              -e MYSQL_USER=root \
              -e MYSQL_PASSWORD=root \
              -e MYSQL_DB=devops \
              ${{ secrets.DOCKERHUB_USERNAME }}/two-tier-backend:latest
          EOF
