name: Deploy Flask Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Flask EC2 Instance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST_FLASK }} >> ~/.ssh/known_hosts

    - name: SSH into Flask EC2 and Deploy App
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST_FLASK }} << 'EOF'
          set -e
          cd ~

          echo "Cloning or Updating Flask App Repo..."
          if [ ! -d "two-tier-flask-app" ]; then
            git clone https://github.com/MUGHEESULHASSAN/final_submission.git two-tier-flask-app
          else
            cd two-tier-flask-app
            git pull origin main
            cd ..
          fi

          cd two-tier-flask-app

          echo "Building Docker Image..."
          sudo docker build -t two-tier-backend .

          echo "Stopping existing container (if any)..."
          sudo docker rm -f flask || true

          echo "Running new Flask container..."
          sudo docker run -d --name flask -p 5000:5000 \
            --network two-tier \
            -e MYSQL_HOST=10.0.2.100 \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=root \
            -e MYSQL_DB=devops \
            two-tier-backend

          echo "Deployment to Flask EC2 completed."
        EOF
